// Shown when a brief isn't in the corpus yet. The server never generates —
// generation happens on the client (the repost MCP/engine, on the user's own
// keys), then publishes here. So we show how, not a "generate" button.

export default function GenerateLocally({ person, topic }: { person: string; topic: string }) {
  const cli = `repost -p ${person} -t "${topic}" --synthesize --publish`;
  return (
    <div className="rounded-lg border border-line bg-card p-6">
      <p className="text-muted">
        No brief yet for <span className="text-foreground font-medium">@{person}</span> on{" "}
        <span className="text-foreground font-medium">&ldquo;{topic}&rdquo;</span>.
      </p>
      <p className="mt-3 text-sm text-muted">
        Briefs are generated by the community using their own X &amp; AI keys, then published here.
        With the repost MCP connected, just ask your agent to research it. Or from the CLI:
      </p>
      <pre className="mt-3 overflow-x-auto rounded-md bg-foreground/5 p-3 text-sm font-mono">
        <code>{cli}</code>
      </pre>
      <p className="mt-3 text-xs text-muted">
        Publishing requires a contributor token. Reading is always free.
      </p>
    </div>
  );
}
